github: ['devgamer', 'coderace']
patreon: 'sprintcarcreator'
open_collective: 'sprintcar-game'
ko_fi: 'sprintcarfund'
tidelift: 'npm/sprintcar-engine'
community_bridge: 'sprintcar-project'
liberapay: 'sprintcardev'
issuehunt: 'sprintcar-issues'
lfx_crowdfunding: 'sprintcar-racing-game'
polar: 'sprintcar-supporter'
buy_me_a_coffee: 'support-sprintcar'
thanks_dev: 'thanksdev-sprintcar'
custom: ['https://donate.sprintcar.com', 'https://paypal.me/sprintcar']
